### ISSUE TITLE
Missing Step in Setup readme.

### ISSUE THREAD

**Issue by rperry99** [novatorem/novatorem#10]
Hello! 

I was trying to add this to my profile, and under the Vercel section, I think it should be said you need to fork your repo. I needed to find a video of someone else adding it to their profile to figure out what I was doing wrong.

**Comment by novatorem** [comment]
Does this make sense: https://github.com/novatorem/novatorem/commit/16c6bb64572dcfc61fb759c5fcc8a7972306f219

Sorry, I never took the time to properly reproduce, didn't think of adding that as a step.

**Comment by rperry99** [comment]
Yeah I think that makes a lot more sense! When I tried to add this to my repo, I was under the impression I was supposed to fork my profile's readme.
