### ISSUE TITLE
Spotify Playing

### ISSUE THREAD

**Issue by Pollob001** [novatorem/novatorem#18]
![Screenshot_2020-12-20 Pollob001 Pollob001](https://user-images.githubusercontent.com/74686750/102694039-7953f500-4259-11eb-9bc4-b1fd6631e868.png)

it's not same.....anyone please

**Comment by novatorem** [comment]
Could you open the debugger and see what you get: https://github.com/novatorem/novatorem/blob/master/SetUp.md#debugging

**Comment by Pollob001** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/74686750/102803381-201fc900-43f3-11eb-9603-8e37992591eb.png)

**Comment by Pollob001** [comment]
bro....any idea ...how to fix this. the refresh token changed randomly.

**Comment by SangTran-127** [comment]
I have the same problem, it not gonna work on my readme 
<img width="1007" alt="Ảnh chụp Màn hình 2021-01-03 lúc 01 49 57" src="https://user-images.githubusercontent.com/76774572/103464597-a202e100-4d67-11eb-92a0-f5c0643e09d7.png">
i follow all the step of the video but in the end, it has some issue

**Comment by novatorem** [comment]
Invalid refresh token means you're using the wrong token, or else didn't map it correctly. Make sure they're set up properly in vercel and that the guide/video was followed through.

@SangTran-127 You should also check the logs, the 500 error could mean anything at this stage.
