### ISSUE TITLE
[FEATURE REQUEST] Mention Now Playing or Recently Played

### ISSUE THREAD

**Issue by saglaniharsh** [novatorem/novatorem#2]
I noticed that when I wasn't playing any song, it just picked up a recently played song from my account. Currently there is no way to know whether the person is actually listening to the song right now or its just something they recently played.
Maybe an icon/text can be added to specify whether the song is Currently playing or recently played.

**Comment by novatorem** [comment]
Doable, although I personally don't want it since most designs would make it jarring.
I can just set it up in a separate branch though.

Two ideas:
* Remove the EQ bar 
* Add an overlay

Any other design thoughts?

**Comment by novatorem** [comment]
If you remove the `#` in front of `contentBar` in [line 81](https://github.com/novatorem/novatorem/blob/94d00e1ca20239f76bf7d064f8831c2fd25086d3/api/spotify-playing.py#L81) of current master, the EQ bar will be hidden when you're in not currently playing anything. If anyone has any better ideas, feel free to reopen.

**Comment by saglaniharsh** [comment]
> 
> 
> Doable, although I personally don't want it since most designs would make it jarring.
> I can just set it up in a separate branch though.
> 
> Two ideas:
> 
>     * Remove the EQ bar
> 
>     * Add an overlay
> 
> 
> Any other design thoughts?

I think removing the EQ bar would be a great Idea! Thanks!
Although, I'm not sure what you mean by an overlay.

**Comment by saglaniharsh** [comment]
OR,
We can also include a title in the card (can be customized)
like we can keep the default as `{ "Listening to" | USER_DEFAULT }`
and if for recent as `{ "Recently listened to" | USER_RECENT_DEFAULT }`
and finally we can also add an option to customize whether user want's the title or not 🤷‍♀️

**Comment by novatorem** [comment]
I see what you mean, doable so I'll set it up and update the setup instructions with config.

**Comment by novatorem** [comment]
Now has a view as such:

![image](https://user-images.githubusercontent.com/16753077/91237617-161de000-e709-11ea-8b17-d98e48c47c44.png)

Description available in [SetUp.md](https://github.com/novatorem/novatorem/blob/master/SetUp.md#customization).

**Comment by yoshimario** [comment]
Where exactly do I put the height of the bar so the eq is not below currently playing text? Thre is no height in the spot where mentioned.

**Comment by lipsilverhand** [comment]
how to customize the background and border color? I don't know to to it please help, thank you so much!
/?background_color=8b0000&border_color=ffffff

@novatorem

**Comment by YasirAltun** [comment]
can you  add  dynamicly change  currently listening music  ( automaticly cahnge   when the music is  change)?

@novatorem
