### ISSUE TITLE
item["album"]["images"]  array can be empty causing index out of range error

### ISSUE THREAD

**Issue by lloydowen8** [novatorem/novatorem#20]
If there is no image associated with a song (if the user is playing local songs from there device for example) then no SVG will be produced. This is due to an index out of bounds error raised in line 105. The "image" array can be empty and should be checked before calling the loadImageB64() function.

A placeholder image should probably be used in the case of the "image" array being empty

**Comment by novatorem** [comment]
Thank you for fixing this!
https://github.com/novatorem/novatorem/pull/21
