### ISSUE TITLE
Something wrong with this

### ISSUE THREAD

**Issue by Aakarsh-B** [novatorem/novatorem#25]
Was working fine earlier on. recently I logged in and saw this. 
https://github-readme-remake.vercel.app/

**Comment by mr-engin3er** [comment]
same problem:
not working  https://novatorem-mr-engin3er.vercel.app/
It's a Spotify now playing app.

**Comment by Aakarsh-B** [comment]
I can't understand what the issue is. It seems okay in some people's readmes

**Comment by ghost** [comment]
- I tried adding "api/spotify" to my URL, the error changed to
"500: INTERNAL_SERVER_ERROR":
https://spotify-now-playing-dllobuz.vercel.app/api/spotify

- As the documentation says, this is an application error, 
I think that we just have to wait for the next updates:
https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED

**Comment by harshptl14** [comment]
Same problem😕

**Comment by pasindujr** [comment]
I'm having the same issue. In the "Function Runtime logs" there is a error saying: 
`Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`

I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?

**Comment by kumar-dheeraj** [comment]
@pasindujr I didn't do anything. It is working again automatically. I just open my Spotify and play a song and then check, it was working again.

**Comment by mr-engin3er** [comment]
@pasindujr I didn't do anything. I just opened Spotify and played a song, it was working again.

**Comment by pasindujr** [comment]
So your player wasn't working before and suddenly starts to work without changing anything @mr-engin3er?

**Comment by mr-engin3er** [comment]
Yes @pasindujr actually I didn't use Spotify for many days. I'm not sure but  I think that was issue. I checked GitHub readme Spotify feature didn't work. I immediately checked Spotify and played a song and problem solved. Maybe it's not useful in your case.

**Comment by Aakarsh-B** [comment]
> I'm having the same issue. In the "Function Runtime logs" there is a error saying:
> `Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`
> 
> I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?

Mine doesn't work. Just rechecked.

**Comment by pasindujr** [comment]
> > I'm having the same issue. In the "Function Runtime logs" there is a error saying:
> > `Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`
> > I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?
> 
> Mine doesn't work. Just rechecked.

What! It worked when I checked as I remember. 😲

**Comment by Aakarsh-B** [comment]
> > > I'm having the same issue. In the "Function Runtime logs" there is a error saying:
> > > `Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`
> > > I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?
> > 
> > 
> > Mine doesn't work. Just rechecked.
> 
> What! It worked when I checked as I remember. 😲

a glitch in the matrix maybe

**Comment by pasindujr** [comment]
> > > > I'm having the same issue. In the "Function Runtime logs" there is a error saying:
> > > > `Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`
> > > > I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?
> > > 
> > > 
> > > Mine doesn't work. Just rechecked.
> > 
> > 
> > What! It worked when I checked as I remember. 😲
> 
> a glitch in the matrix maybe

![image](https://user-images.githubusercontent.com/61911519/119246894-db1ae100-bba2-11eb-9382-7a054dce8f68.png)

**Comment by Aakarsh-B** [comment]
> > > > > I'm having the same issue. In the "Function Runtime logs" there is a error saying:
> > > > > `Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`
> > > > > I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?
> > > > 
> > > > 
> > > > Mine doesn't work. Just rechecked.
> > > 
> > > 
> > > What! It worked when I checked as I remember. 😲
> > 
> > 
> > a glitch in the matrix maybe
> 
> ![image](https://user-images.githubusercontent.com/61911519/119246894-db1ae100-bba2-11eb-9382-7a054dce8f68.png)

and how did you make the magic happen. its a broken link on my profile readme.

**Comment by pasindujr** [comment]
> > > > > > I'm having the same issue. In the "Function Runtime logs" there is a error saying:
> > > > > > `Unable to import module 'vc__handler__python': No module named 'werkzeug._compat'`
> > > > > > I see @Aakarsh-B's and @mr-engin3er's players are working fine. How did you guys fix that?
> > > > > 
> > > > > 
> > > > > Mine doesn't work. Just rechecked.
> > > > 
> > > > 
> > > > What! It worked when I checked as I remember. 😲
> > > 
> > > 
> > > a glitch in the matrix maybe
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61911519/119246894-db1ae100-bba2-11eb-9382-7a054dce8f68.png)
> 
> and how did you make the magic happen. its a broken link on my profile readme.

I just used the above link you have posted.
https://github-readme-remake.vercel.app/api/spotify

**Comment by Khroners** [comment]
I found a fix. You need to edit the requirements.txt file and change the flesk version to 1.1.4.  Thanks to this : https://stackoverflow.com/questions/67553537/getting-error-with-deployed-serverless-flask-app-on-aws-no-module-named-werkze

**Comment by harshptl14** [comment]
@Khroners it worked🙌

**Comment by pasindujr** [comment]
Holy it worked! Thanks @Khroners!

**Comment by Aakarsh-B** [comment]
still the same in my case, is there something im missing?
https://vercel.com/aakarsh-b/spotifyonreadme

**Comment by pasindujr** [comment]
> still the same in my case, is there something im missing?
> https://vercel.com/aakarsh-b/spotifyonreadme

https://github-readme-remake.vercel.app/api/spotify this is not the URL u have put in your readme. this works.

**Comment by Aakarsh-B** [comment]
> > still the same in my case, is there something im missing?
> > https://vercel.com/aakarsh-b/spotifyonreadme
> 
> https://github-readme-remake.vercel.app/api/spotify this is not the URL u have put in your readme. this works.

FINALLY!
Thanks everyone! :)
