### ISSUE TITLE
Could not able to integrate, please help.

### ISSUE THREAD

**Issue by SupriyaGo** [novatorem/novatorem#33]
I have followed all the steps but at the end, the alt test is showing in my readme file. Please help

**Comment by novatorem** [comment]
Could you follow the debugging section here: https://github.com/novatorem/novatorem/blob/master/SetUp.md#debugging

If there are any logs to look over, that'd help too.

**Comment by SupriyaGo** [comment]
@novatorem yes sir, I also have watched the video but it is not working.

**Comment by novatorem** [comment]
From the debugging steps above, were there any logs that provided the issue?

Anything that looks like the image attached
![image](https://user-images.githubusercontent.com/16753077/121818329-82e07780-cc54-11eb-90ab-7fe8b5e1dae5.png)

**Comment by Lowgy** [comment]
I was wondering if this was resolved at all? As I am currently also only seeing the ALT text after following the guide.
Also zero logs have been generated in my Vercel Functions Dashboard.

**Comment by Lowgy** [comment]
> I was wondering if this was resolved at all? As I am currently also only seeing the ALT text after following the guide.
> Also zero logs have been generated in my Vercel Functions Dashboard.

Turns out I was pointing to the wrong domain in the readme.. ignore this 🙃
