### ISSUE TITLE
What is the Username ? 

### ISSUE THREAD

**Issue by DarshGupta1910** [novatorem/novatorem#34]
<p> [![Spotify](https://USER_NAME.vercel.app/api/spotify)](https://open.spotify.com/user/USER_NAME) </p>

If the Username here is Spotify's Username what is the need for deployment on Vercel? 

I'm new to coding I may sound silly. 

I have done all the steps shown in the <a href= "https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s">Guide</a> but I'm not able to integrate please help !!!

**Comment by novatorem** [comment]
Username would be your vercel username.

The deployment to vercel is to be able to get your information from spotify via their API, and then load the HTML so that it can appear in your ReadMe.

----

You mention being unable to run it. From the debugging steps, did you follow them to the part where you can see logs?
What logs are available from the vercel application?

**Comment by DarshGupta1910** [comment]
I can see two types of logs - built log and function log

I'm sharing the screenshot of both 

![image](https://user-images.githubusercontent.com/73016212/121819527-28263a80-ccab-11eb-8fb9-b84546f16a60.png)

![image](https://user-images.githubusercontent.com/73016212/121819559-5b68c980-ccab-11eb-9975-c9c08834f47f.png)

This is just showing loading from a long time 
![image](https://user-images.githubusercontent.com/73016212/121819584-7b988880-ccab-11eb-9d6e-147fcfda9e2b.png)



![image](https://user-images.githubusercontent.com/73016212/121819634-d29e5d80-ccab-11eb-9f65-42d8011599d3.png)

I replaced the username with my vercel's username then also It's not working

**Comment by novatorem** [comment]
The loading implies you haven't sent any requests out.

Reaching out to your address: https://novatorem-darshgupta1910.vercel.app/api/spotify

I see that there is an error somewhere:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

You'll need to provide more info based on logs (function logs, as the build went fine).
Couple of things to note:
- [ ] Spotify Premium
- [ ] Proper environment variables set

**Comment by DarshGupta1910** [comment]
Ok thanks @novatorem 
And do I need to have spotify premium ?

**Comment by DarshGupta1910** [comment]
@novatorem How to provide more info based on function logs?

**Comment by DarshGupta1910** [comment]
@novatorem can u please reply?

**Comment by ahmeedev** [comment]
> @novatorem can u please reply?

Bro, I'm also stuck.
what is the solution?

**Comment by ahmeedev** [comment]
> @novatorem can u please reply?

![image](https://user-images.githubusercontent.com/75003816/132084506-f0732acd-0b4d-432c-b9ce-de044f259cf8.png)

**Comment by ahmeedev** [comment]
@DarshGupta1910  Bro can you help me?

**Comment by ahmeedev** [comment]
https://ahmadbintariq4u.vercel.app/api/spotify
