### ISSUE TITLE
500 error when podcast playing

### ISSUE THREAD

**Issue by lizzykerrigan** [novatorem/novatorem#4]
Hey! Love this script so far, but noticed there's an issue when playing podcasts - in the `makeSVG()` function, `item` is assigned to `data["item"]`, but this comes back as `None` when a podcast is currently playing. This can be fixed by changing the conditional to this:

`if data == {} or data["item"] == None:`

I'm not sure if podcast playing information can be obtained, but for the time being, I'd be happy to open a PR to fix this if you like? Just so that the `recentPlays` info is returned instead of a 500 error :slightly_smiling_face:

**Comment by novatorem** [comment]
Good find! 

I'll merge in the PR if you make it, but I'll also look into grabbing the information for podcasts for those who use them.

**Comment by ajmeese7** [comment]
@novatorem have you considered applying for the GitHub sponsorship program? I'm not rich by any means, but I'd love to show my appreciation for your work if you can get accepted.

**Comment by novatorem** [comment]
Thanks for the PR, closed thanks to https://github.com/novatorem/novatorem/pull/6

@ajmeese7 Thank you, but there's no need - if you have any feature requests/bug fixes (will look into podcasts), let me know.
