### ISSUE TITLE
After running the curl command an error pops up

### ISSUE THREAD

**Issue by shimanto-rehman** [novatorem/novatorem#42]
It says:  ```{"error":"invalid_client","error_description":"Invalid client secret"}```
Why I am getting this error???
I can't get the Spotify Refresh Token

**Comment by alexsandersilv** [comment]
> It says: `{"error":"invalid_client","error_description":"Invalid client secret"}` Why I am getting this error??? I can't get the Spotify Refresh Token


Hi @shimanto-rehman ,I was also having the same error,

You must have put it in the wrong order, I'll give you an example of how it should be done with these two example ids:

Client ID: 777777777
Client Secret: 88888888888

Paste in Encode input:
777777777:88888888888

Copy the result from Decode:
Nzc3Nzc3Nzc3Ojg4ODg4ODg4ODg4Cg==

Now in the terminal:
```sh
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Basic Nzc3Nzc3Nzc3Ojg4ODg4ODg4ODg4Cg==" -d "grant_type=authorization_code&redirect_uri=http://localhost/callback/&code={CODE}" https://accounts.spotify.com/api/token
```

Your result will likely be this:
```json
{
  "access_token": "**********",
  "token_type": "Bearer",
  "expires_in": 3600,
  "refresh_token": " YOU TOKEN ",
  "scope": "user-read-currently-playing user-read-recently-played"
}
```
