### ISSUE TITLE
spotify music

### ISSUE THREAD

**Issue by Pollob001** [novatorem/novatorem#49]
Hi....i need help...
why spotify is not working in my profile....i did everything according to setup.md...
but i am not understanding why its not working...
if anyone give me solution ....it will be so much helpful for me...
thank you

**Comment by sehoon787** [comment]
Did you try to listen any other music with your Spotify account?

**Comment by novatorem** [comment]
Looks like you did get it up and running, but for future viewers, please use the debug steps:  
https://github.com/novatorem/novatorem/blob/master/SetUp.md#debugging
