### ISSUE TITLE
I did the whole process but it doesn't work for me, help me

### ISSUE THREAD

**Issue by AnderMendoza** [novatorem/novatorem#50]
I did the whole process with Vercel but in the domain it throws me a "500 internal server error" I don't know what could have gone wrong.
My domain in vercel is: https://spotify-now-playing-df0d0ezcc-andermendoza.vercel.app/api/spotify
Vercel hosted project: https://vercel.com/andermendoza/spotify-now-playing
![Captura de pantalla 2022-09-06 150633](https://user-images.githubusercontent.com/80181518/188729117-be26248a-5509-40d5-84fb-2a46979afb46.png)
![Captura de pantalla 2022-09-06 150659](https://user-images.githubusercontent.com/80181518/188729130-7496c315-c083-4860-b5c3-da0fe3bfc8d4.png)

**Comment by CrazeDoc** [comment]
Same thing showing on my side as well :(

Did the entire process documented on the setup.md, but after deploying it is showing the Internal Server Error...

Domain link: https://novatorem-five-swart.vercel.app/api/spotify

![image](https://user-images.githubusercontent.com/81755723/204121824-fde81e46-d1b3-4089-b081-60d7fd717ca8.png)

**Comment by novatorem** [comment]
Please attempt to follow the debug steps in https://github.com/novatorem/novatorem/blob/master/SetUp.md#debugging - does look like [AakashRao-dev](https://github.com/AakashRao-dev) got it working though.
