### ISSUE TITLE
Cool App! Current bug `Unable to import module 'vc__handler__python'`

### ISSUE THREAD

**Issue by bmitchinson** [novatorem/novatorem#53]
Current vercel bug:

![image](https://user-images.githubusercontent.com/33632286/202525167-a495cf3b-2b74-461d-90b3-a6dd3e2a7550.png)

```
[GET] /api/spotify
11:09:23:22
[ERROR] Runtime.ImportModuleError: Unable to import module 'vc__handler__python': cannot import name 'escape' from 'jinja2' (/var/task/jinja2/__init__.py)
Traceback (most recent call last):
```

Might take a look at trying to fix this, thanks for the setup instructions with links! I have a feeling it's 90% working but I'm just missing some package definitions. If I make a fix I'll throw a PR this way.

**Comment by ZEUSGMJ** [comment]
Hey, any update on this? Currently facing this issue when trying to deploy it on Vercel.
![image](https://user-images.githubusercontent.com/42777277/229248197-c82079de-a2dd-43a4-8b46-d69a06dac59c.png)

**Comment by ZEUSGMJ** [comment]
I was able to fix my issue, by setting these in the `requirements.txt` which is in the root folder.

```
autopep8==1.6.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
Flask==2.2.3
gunicorn==20.1.0
idna==2.10
itsdangerous==1.1.0
Jinja2==3.1.2
markupsafe==2.1.2
pycodestyle==2.8.0
python-dotenv==0.14.0
requests==2.24.0
toml==0.10.2
urllib3==1.25.11
Werkzeug==1.0.1
colorthief==0.2.1
```

and this in `api/requirements.txt`

```
flask==2.2.3
requests==2.24.0
python-dotenv==0.14.0
colorthief==0.2.1
```
