### ISSUE TITLE
[DOC Update Request] Update Setup.md

### ISSUE THREAD

**Issue by Sourjaya** [novatorem/novatorem#58]
### Embedding links in the md file to redirect to the line of code in `spotify.html.j2`

![Screenshot 2023-01-29 222222](https://user-images.githubusercontent.com/49400992/215345771-6368398e-a700-4eaa-b995-625a7f71ebe9.png)

- while following the steps, it took me a while to remove the `comment tag` from the above mentioned lines of code because the exact location of the lines are not mentioned clearly in the documentation.

**Comment by novatorem** [comment]
Would need to link to a specific point in time, else as the repo changes will have to update the time.
Should be easier to not link, and require people to search for it.
