### ISSUE TITLE
Got error curling link

### ISSUE THREAD

**Issue by RaymondJiang1** [novatorem/novatorem#8]
I have been getting the same error every time I try to curl the specified link. I get this error. `{"error":"invalid_client","error_description":"Invalid client secret"}% `. I have followed the steps up until now.  (I don't know if this effects it but I am using terminal so idk.)

**Comment by RaymondJiang1** [comment]
My curl url looks like this. `curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Basic {TheBase64Thing}" -d "grant_type=authorization_code&redirect_uri=http://localhost/callback/&code={ThecodeIgotfromlocalhost}" https://accounts.spotify.com/api/token`

**Comment by novatorem** [comment]
Shouldn't be affected if you're using the terminal, I just put in the link for people with different shells.

Anyway, looks like `Invalid client secret` is the issue really, so just make sure if grabbed the right client secret?
Don't share it publicly though, and someone made a [video](https://youtu.be/n6d4KHSKqGk?t=615) on the setup, which should help.

**Comment by RaymondJiang1** [comment]
Thank you so much! I followed it and it didn't work for some reason. Thanks for linking a video to one of my favorite coding youtubers! I will let you know if it will work! Thanks!

**Comment by RaymondJiang1** [comment]
No matter what I do, I still get the same error. I followed the video and it still didn't work. I even used a different application and still didn't work

**Comment by RaymondJiang1** [comment]
Never mind. I figured it out! Thank you so much!

**Comment by novatorem** [comment]
Oh? What was the issue?

Others might be up against the same challenge, so any help would be useful.

**Comment by RaymondJiang1** [comment]
So I didn't delete the space between the semi-colon when you do the Base64. Just saying but your Base64 code thingy should **ALWAYS** end in a ```=``` no matter what.

**Comment by arshsahzad** [comment]
> Never mind. I figured it out! Thank you so much!

I'm getting the same error as your's, how did you resolve it??

**Comment by siddiquidotsh** [comment]
> Never mind. I figured it out! Thank you so much!

I'm getting the same error as your's, how did you resolve it??
