### ISSUE TITLE
This Serverless Function has crashed.

### ISSUE THREAD

**Issue by 4kshi7** [novatorem/novatorem#82]
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED

**Comment by lexzer42** [comment]
If you encounter this problem, follow these steps to resolve it:

1. Go to Vercel.
2. Navigate to Your Project.
3. Go to Settings.
4. Select General.
5. Change the Node.js Version to either 18.x or 16.x.

This should resolve the issue

**Comment by 4kshi7** [comment]
Damn this really worked thanks brother

**Comment by Zimerzel** [comment]
To anyone else who was still stuck after making this change, redeploy the site. The node version requires redeploy to take effect
