### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by Cristuker** [novatorem/novatorem#9]
When i try to access the deploy project on `/api/spotify" i have 404 not found but my files is here hwhen i acess https://novatorem-iy3pwkfqq.vercel.app/ and when i usei https://novatorem-iy3pwkfqq.vercel.app/api/spotify dont work and i have other problem 

.py on end spotify don work 

>Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by novatorem** [comment]
Please follow the steps in the [debugging section of the setup](https://github.com/novatorem/novatorem/blob/master/SetUp.md#debugging), and if it persists, share your logs here.

**Comment by Cristuker** [comment]
Just load, i try to view again, but do have generate logs, just 404

![Captura de tela de 2020-08-31 19-12-30](https://user-images.githubusercontent.com/42705870/91773948-2416a980-ebbe-11ea-90f1-0255de1909e0.png)

![Captura de tela de 2020-08-31 19-12-24](https://user-images.githubusercontent.com/42705870/91773944-22e57c80-ebbe-11ea-9302-1ecc7c87ba19.png)

**Comment by novatorem** [comment]
Did you follow the video guide to make sure you didn't miss any steps?

Any info from the build logs?

**Comment by Cristuker** [comment]
yes and yes, i have all information, the name of env variables is ok, i gonna try again tomorow

**Comment by Cristuker** [comment]
probably i used the wrong url, i try with this https://novatorem.cristuker.vercel.app/api/spotify.py and works fine. Thanks for help.
